sudo: required

before_install: 
  - docker build -f Dockerfile.dev -t react_multiapp_client ./client

script: 
  - pwd
  - ls
  - docker run -e CI=true react_multiapp_client npm run test

after_success: 
  - docker build -f Dockerfile.dev -t react_multiapp_client ./client
  - docker build -f Dockerfile.dev -t react_multiapp_worker ./worker
  - docker build -f Dockerfile.dev -t react_multiapp_server ./server
  - docker build -f Dockerfile.dev -t react_multiapp_nginx ./nginx