sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t home1docker1/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true home1docker1/react-test npm test

after_success:
  - docker build -t home1docker1/multi-client ./client
  - docker build -t home1docker1/multi-nginx ./nginx
  - docker build -t home1docker1/multi-server ./server
  - docker build -t home1docker1/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_HUB_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push home1docker1/multi-client
  - docker push home1docker1/multi-nginx
  - docker push home1docker1/multi-server
  - docker push home1docker1/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'react_multiapp'
  env: 'Reactmultiapp-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-279955776817'
  bucket_path: 'react_multiapp'
  on:
    branch: main
  access_key_id: $FULL_KEY
  secret_access_key: $FULL_SECRET
