sudo: required

before_install: 
  - cd ./client; docker build -f Dockerfile.dev -t react_multiapp_client ./client

script: 
  - docker run -e CI=true react_multiapp_client npm run test

after_success: 
  - docker build -f Dockerfile.dev -t react_multiapp_client ./client
  - cd ..; cd ./worker; docker build -f Dockerfile.dev -t react_multiapp_worker ./worker
  - cd ..; cd ./server; docker build -f Dockerfile.dev -t react_multiapp_server ./server
  - cd ..; cd ./ngnix; docker build -f Dockerfile.dev -t react_multiapp_nginx ./nginx