sudo: required

before_install: 
  - cd ./client; docker build -f Dockerfile.dev -t react_multiapp_client .

script: 
  - docker run -e CI=true react_multiapp_client npm run test

after_success: 
  - docker build -f Dockerfile -t home1docker1/react_multiapp_client:1.0.0 .
  - cd ..; cd ./worker; docker build -f Dockerfile.dev -t home1docker1/react_multiapp_worker:1.0.0 .
  - cd ..; cd ./server; docker build -f Dockerfile.dev -t home1docker1/react_multiapp_server:1.0.0 .
  - cd ..; cd ./nginx; docker build -f Dockerfile.dev -t home1docker1/react_multiapp_nginx:1.0.0 .
  - echo "$DOCKER_HUB_PASS" | docker login -u "$DOCKER_ID" --password-stdin 
  - docker push home1docker1/react_multiapp_client:1.0.0
  - docker push home1docker1/react_multiapp_worker:1.0.0
  - docker push home1docker1/react_multiapp_server:1.0.0
  - docker push home1docker1/react_multiapp_nginx:1.0.0

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "react_multiapp"
  env: "Reactmultiapp-env"
  bucket_name: "elasticbeanstalk-eu-central-1-279955776817"
  bucket_path: "react_multiapp"
  on:
    branch: main
  access_key_id: $AWS_EB_ACCESS_KEY
  secret_access_key: $AWS_EB_SECRET