version: '3.8'

services:

  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
    env_file:
      - ./server/.env
    depends_on:
      - pg
      - redis
    restart: always

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - ./worker:/usr/app
      - /usr/app/node_modules
    env_file:
      - ./worker/.env
    depends_on:
      - api
      - redis

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/usr/app
      - /usr/app/node_modules
    depends_on:
      - api
      - worker
    restart: always
    environment:
      - WDS_SOCKET_PORT=0

  pg:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=user
    restart: always

  redis:
    image: redis:latest
    restart: always

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    depends_on:
      - api
      - client
    ports:
      - 8080:80
    restart: always