    version: "3.8"

    services:

      client:
        image: "home1docker1/react_multiapp_client"
        mem_limit: 128m
        hostname: client

      server:
        image: "home1docker1/react_multiapp_server"
        mem_limit: 128m
        hostname: api
        environment:
          - REDIS_HOST=$REDIS_HOST
          - REDIS_PORT=$REDIS_PORT
          - PGUSER=$PGUSER
          - PGHOST=$PGHOST
          - PGDATABASE=$PGDATABASE
          - PGPASSWORD=$PGPASSWORD
          - PGPORT=$PGPORT

      worker:
        image: "home1docker1/react_multiapp_worker"
        mem_limit: 128m
        hostname: worker
        environment:
          - REDIS_HOST=$REDIS_HOST
          - REDIS_PORT=$REDIS_PORT

      nginx:
        image: "home1docker1/react_multiapp_nginx"
        mem_limit: 128m
        hostname: nginx
        ports:
          - "80:80"